### ISSUE TITLE
Any examples of using webdav-handler-rs with warp?

### ISSUE THREAD

**Issue by charlesdaniel** [miquels/webdav-handler-rs#1]
Hi are there any examples of how to use webdav-handler with warp? The documentation says it should be supported but I'm not sure how to get a hold of the Request from warp to pass it to webdav-handler.

**Comment by miquels** [comment]
As far as I know, there is no way to use webdav-handler with warp. I was 
also quite surprised when playing around with warp that there is no way 
to simply get hold of the Request. Seems like an oversight in the warp api.

Mike.

**Comment by miquels** [comment]
Ok, so it is possible. I added [an example for Warp](https://github.com/miquels/webdav-handler-rs/blob/master/examples/warp.rs)

**Comment by miquels** [comment]
In fact, I just added a [warp-compat module](https://docs.rs/webdav-handler/0.2.0-alpha.4/webdav_handler/warp/index.html). And for good measure, one for actix-web as well.

**Comment by charlesdaniel** [comment]
@miquels You're awesome! Thank you so much for doing that! This is a really great and super useful module that seems to just work. Thanks again!
