### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by sj6219** [miquels/webdav-handler-rs#2]
It doesn't work in Windows environments.
Do you have any plans to release Windows version?

**Comment by miquels** [comment]
Well, I don't develop on windows, so .. no. However, I might consider adding windows support if someone does the work and sends a pull request.

**Comment by DuckerMan** [comment]
Hi. What exactly doesn't work?

**Comment by sj6219** [comment]
Once the UNIX environment is not familiar, it is difficult to make it run. 
So I think it will be hard to port. 
It seems too much for me to make a Windows version without understanding the program source.
I'm trying to find an open source that runs on Windows.

Thank you.
