### ISSUE TITLE
Tightening the visibility and the trait boundary of async_stream

### ISSUE THREAD

**Issue by Qwaz** [miquels/webdav-handler-rs#6]
Currently, `async_stream` module that contains Sync/Send bypass is hidden but still reachable from the user side of this crate. This theoretically allows users to cause data races using safe APIs of this crate.

I would like to suggest (1) tightening the visibility of `async_stream` module to `pub(crate)` if possible, and (2) adding `I: Send` and `E: Send` trait bounds to Sync/Send trait implementation for `Sender` as an additional safety measure to prevent potential in-crate misuses.

https://github.com/miquels/webdav-handler-rs/blob/0acc45beda2ab42b022a8e9ef141edfc32278c78/src/async_stream.rs#L80-L81

**Comment by miquels** [comment]
Forgot to say, thanks :)
