### ISSUE TITLE
WebDAV as cgi-bin program?

### ISSUE THREAD

**Issue by stokito** [miquels/webdav-handler-rs#9]
I need to add WebDAV to an old small 4mb router.
The router already has a simple http daemon which supports CGI (busybox httpd or uhttpd, I can use any of them).
So I want to develop a small WebDAV cgi program: single threaded, no locks/if-match, with only basic features and parses stdin and writes to stdout.
And for safeness it would be better to use Rust but I newer used it before.
Looks like your crate is a good library to start but it I'm afraid that it uses async and has a lot of dependencies so resulted executable will be too big.
So the question is: how do you think, is this something that possible to do with webdav-handler crate without forking and massive changes?

**Comment by miquels** [comment]
The webdav library has not been written with small/embedded systems in mind, so I don't think it will run on your router. Rewriting it as a CGI program is going to be more work than just starting from scratch, I think.

If you want to build something in rust, this is more bare-bones: [hyperdav-server](https://github.com/tylerwhall/hyperdav-server). Or, for something of-the-shelf, [lighttpd](https://www.lighttpd.net/) is also small and has webdav support.
